Adds missing examples in docs for the `gitlab_*_variable(s)` data sources
gitlabhq/terraform-provider-gitlab pull request #1051
Opened 2022-05-02 12:23 UTC by timofurrer

This change set adds the missing examples to the documentation of the recently added `gitlab_*_variable(s)` data sources

2022-05-06 02:15 UTC, PatrickRice-KSC requested changes
Couple small copy/paste errors, otherwise looks good!

2022-05-06 02:15 UTC, PatrickRice-KSC commented on examples/data-sources/gitlab_group_variable/data-source.tf
> +  project           = "my/example/group"
```suggestion
  group = "my/example/group"
```

I think this is supposed to be group 😄

2022-05-06 02:15 UTC, PatrickRice-KSC commented on examples/data-sources/gitlab_group_variables/data-source.tf
> +  project           = "my/example/group"
```suggestion
  group            = "my/example/group"
```

Same here 🙂

2022-05-13 07:14 UTC, armsnyder approved these changes

2022-05-13 07:16 UTC, merged