Parallelize most of the acceptance tests
gitlabhq/terraform-provider-gitlab pull request #1126
Opened 2022-06-08 15:50 UTC by timofurrer

The only ones which are not yet `resource.ParallelTest`s are the deploy key tests
which reuse keys.

I suggest that we tackle this later.

2022-06-13 21:29 UTC, PatrickRice-KSC commented on internal/provider/data_source_gitlab_project_issues_test.go
>  	testIssues := testAccCreateProjectIssues(t, testProject.ID, 25)
Note for other reviewers (if any choose to check this out 😄  )- even though CreatProjectIssues doesn't clean up after itself, the issues will be deleted when the project does.

2022-06-13 22:13 UTC, PatrickRice-KSC requested changes
I think we need to add a config here to limit the gitpod environment to 2 parallel tests. It looks like it defaults to 5 parallel tests, and the GitLab environment spun up in GitPod gets a lot of deadlock failures on tests when it runs 5 at once :-/

I dropped tests one by one until I got down to 2 and was getting pretty reliably success rates. It was pretty reliable at 3 also, but I was still hitting occasional failures.

2022-06-14 07:16 UTC, timofurrer commented
@PatrickRice-KSC The GitPod setup is a good point. We should be able to simply set `-parallel 2` when running the tests or maybe more "out-of-the-box" set `GOMAXPROCS=2` for the GitPod environment?

2022-06-14 22:32 UTC, PatrickRice-KSC commented
> We should be able to simply set -parallel 2 when running the tests or maybe more "out-of-the-box" set GOMAXPROCS=2 for the GitPod environment?

@timofurrer  - Yeah, the `-parallel=2` flag was exactly what I was using to test in gitpod, and we can just add it to the test args in the vscode settings where we already have stuff like the GITLAB_TOKEN and such 🙂

2022-06-17 07:11 UTC, timofurrer commented
> and we can just add it to the test args in the vscode settings 

@PatrickRice-KSC okay, this may be good enough for now. Even though people use vscode outside of GitPod - it's a good start for now :)

2022-06-18 00:34 UTC, PatrickRice-KSC approved these changes
LGTM! Let's ship it!

2022-06-18 00:34 UTC, merged