update CONTRIBUTING and README documentation
gitlabhq/terraform-provider-gitlab pull request #1300
Opened 2022-10-27 02:36 UTC by PatrickRice-KSC

## Description

This PR adds a minor note to the CONTRIBUTING.md about the known issue with the m1 development evnrionment (and assumes the same is true of the m2 processor since it's likely an ARM issue).

I also took this opportunity to update the discord link in our README.md.

### PR Checklist Acknowledgement

- [ ] I acknowledge that all of the following items are true, where applicable:
  - Resource attributes match 1:1 the names and structure of the API resource in [the GitLab API documentation](https://docs.gitlab.com/ee/api/).
  - [Examples](https://github.com/gitlabhq/terraform-provider-gitlab/tree/main/examples) are updated with:
    - A \*.tf file for the resource/s with at least one usage example
    - A \*.sh file for the resource/s with an import example (if applicable)
  - New resources have at minimum a basic test with three steps:
    - Create the resource
    - Update the attributes
    - Import the resource
  - No new `//lintignore` comments were copied from existing code. (Linter rules are meant to be enforced on new code.)

2022-10-28 08:24 UTC, timofurrer requested changes

2022-10-28 08:24 UTC, timofurrer commented on CONTRIBUTING.md
> +The apple silicon environments currently have an issue where the local GitLab container will now start to run tests. We recommend that you use GitPod for developing the
```suggestion
The apple silicon environments currently have an issue where the local GitLab container will not start to run tests. We recommend that you use GitPod for developing the 
```

2022-10-29 02:04 UTC, PatrickRice-KSC commented on CONTRIBUTING.md
> +The apple silicon environments currently have an issue where the local GitLab container will now start to run tests. We recommend that you use GitPod for developing the
nice catch, thanks!

2022-10-30 02:49 UTC, Shocktrooper submitted a review, later dismissed

2022-11-03 07:37 UTC, timofurrer commented
Could you please rebase onto the latest main (see #1304)?

2022-11-04 15:07 UTC, Shocktrooper approved these changes

2022-11-04 15:09 UTC, Shocktrooper commented
@timofurrer I think you need to mark your request as done assuming there are no more changes to make before this can be merged

2022-11-06 15:43 UTC, timofurrer approved these changes

2022-11-06 15:43 UTC, merged