Update text matrix for the 3 most recent versions
gitlabhq/terraform-provider-gitlab pull request #1302
Opened 2022-10-27 02:49 UTC by PatrickRice-KSC

## Description

This PR just updates the test matrix to use the 3 most recent versions.

Closes #1301

### PR Checklist Acknowledgement

- [ ] I acknowledge that all of the following items are true, where applicable:
  - Resource attributes match 1:1 the names and structure of the API resource in [the GitLab API documentation](https://docs.gitlab.com/ee/api/).
  - [Examples](https://github.com/gitlabhq/terraform-provider-gitlab/tree/main/examples) are updated with:
    - A \*.tf file for the resource/s with at least one usage example
    - A \*.sh file for the resource/s with an import example (if applicable)
  - New resources have at minimum a basic test with three steps:
    - Create the resource
    - Update the attributes
    - Import the resource
  - No new `//lintignore` comments were copied from existing code. (Linter rules are meant to be enforced on new code.)

2022-10-28 08:46 UTC, timofurrer commented
most tests are failing because of https://github.com/gitlabhq/terraform-provider-gitlab/issues/1304

2022-10-29 02:02 UTC, PatrickRice-KSC commented
Yeah, I think there are a couple that are new failures, but need to get the current ones solved before I can confirm that.

2022-11-03 07:37 UTC, timofurrer commented
Could you please rebase onto the latest main (see #1304)?

2022-11-04 13:17 UTC, PatrickRice-KSC commented
rebased - I think we're going to have some test failures just based on what I was seeing before, but we'll see here in a bit :)

2022-11-04 14:21 UTC, PatrickRice-KSC commented
@timofurrer  | @armsnyder  | @Shocktrooper  - This is ready for review/merge. Apparently 100% of the failed tests were related to license issues, which is good; makes more sense 😄

2022-11-04 14:45 UTC, Shocktrooper commented
@PatrickRice-KSC Security updates are out as of 2 days ago should we target those?
https://about.gitlab.com/releases/categories/releases/

2022-11-04 15:08 UTC, PatrickRice-KSC commented
@Shocktrooper  - good catch, sure!

2022-11-04 15:23 UTC, Shocktrooper requested changes

2022-11-04 15:23 UTC, Shocktrooper commented on .github/workflows/pr-acceptance-ce.yml
> +        gitlab-version: ["15.3.5-ce.0", "15.4.3-ce.0", "15.5.2-ce.0"]
```suggestion
        gitlab-version: ["15.3.5-ce.0", "15.4.4-ce.0", "15.5.2-ce.0"]
```

2022-11-04 15:23 UTC, Shocktrooper commented on .github/workflows/push.yml
> +        gitlab-version: ["15.3.5-ce.0", "15.4.3-ce.0", "15.5.2-ce.0"]
```suggestion
        gitlab-version: ["15.3.5-ce.0", "15.4.4-ce.0", "15.5.2-ce.0"]
```

2022-11-06 15:43 UTC, timofurrer approved these changes

2022-11-06 15:43 UTC, merged