Add new data source gitlab_group_membership
gitlabhq/terraform-provider-gitlab pull request #264
Opened 2020-02-25 10:19 UTC by ilpianista

As per subject.

2020-06-01 07:01 UTC, vymarkov commented
@ilpianista hi, thanks for awesome work ! 

Are you going to finish this PR in near time?

2020-06-01 08:09 UTC, ilpianista commented
> @ilpianista hi, thanks for awesome work !
> 
> Are you going to finish this PR in near time?

Hi, what's missing from your point of view?

2020-06-10 05:15 UTC, vymarkov commented
> > @ilpianista hi, thanks for awesome work !
> > Are you going to finish this PR in near time?
> 
> Hi, what's missing from your point of view?

Hi, looks like there were issues with tests, now everything is ok, I hope it will be merged very soon :)

2020-07-07 10:57 UTC, TheMacStack commented
This would likely solve a painful issue we are facing with trying to automate changing of users sync'd to a gitlab.com group via SCIM from guest to dev or similar on child projects, is there any knowing when it might be merged?

2020-07-18 13:29 UTC, ilpianista commented
Let's try by pinging @ringods.

2020-09-07 20:02 UTC, armsnyder requested changes
Hey @ilpianista it looks like your new doc page is not added to the index file (website/gitlab.erb). Can you add it?

2020-09-08 09:25 UTC, ilpianista commented
@armsnyder done, thanks!

2020-09-08 15:30 UTC, armsnyder approved these changes
Thanks!

2020-09-08 15:34 UTC, armsnyder requested changes

2020-09-08 15:34 UTC, armsnyder commented on website/gitlab.erb
> +                    <a href="/docs/providers/gitlab/d/group_membership.html">gitlab_group membership</a>
Looks like a typo here 
```suggestion
                    <a href="/docs/providers/gitlab/d/group_membership.html">gitlab_group_membership</a>
```

2020-09-08 15:56 UTC, armsnyder approved these changes

2020-09-08 15:56 UTC, merged