add support for importing protected branches and tags
gitlabhq/terraform-provider-gitlab pull request #345
Opened 2020-06-23 08:11 UTC by aquavitae

2020-08-08 04:39 UTC, armsnyder commented
Can you modify the tests to add a TestStep with `ImportState: true`?

2020-09-12 23:24 UTC, armsnyder commented
@aquavitae Are you still working on this PR?

2022-01-23 16:57 UTC, timofurrer requested changes
Please rebase to latest master for SDK v2 changes and pls accept the suggestions. Otherwise, LGTM.

2022-01-23 16:57 UTC, timofurrer commented on gitlab/resource_gitlab_branch_protection.go
> +			State: schema.ImportStatePassthrough,
```suggestion
			StateContext: schema.ImportStatePassthroughContext,
```

2022-01-23 16:57 UTC, timofurrer commented on gitlab/resource_gitlab_tag_protection.go
> +			State: schema.ImportStatePassthrough,
```suggestion
			StateContext: schema.ImportStatePassthroughContext,
```

2022-02-06 04:46 UTC, armsnyder commented
Both of these importers were also added in #318 so I'm going to close this PR. Thanks!

2022-02-06 04:46 UTC, closed without merging