Support group shared_with_groups
gitlabhq/terraform-provider-gitlab pull request #369
Opened 2020-07-31 06:55 UTC by horjulf

Fixes #300, opening PR for feedback regarding the shared functions with the project resource.
Will add `gitlab_group_share_group` if all looks good.

Pending upstream https://github.com/xanzy/go-gitlab/pull/894.

2020-08-09 08:45 UTC, horjulf commented
This is now ready for review and merge.

2020-09-03 07:03 UTC, maxenced commented
Hi, any chance we see this PR accepted ? LGTM (don't have a strong go lvl though), and would love to see it merged !

2020-09-10 11:26 UTC, maxenced commented
@armsnyder anything I can do to help this one get accepted ? 
Though the share-group-with-group feature on gitlab side still has a couple of issues to be solved, API seems stable enough.
We tested this locally with success (2000+ projects / 700 users on gitlab instance, only relying on group based permisssions).

2020-09-12 19:19 UTC, armsnyder requested changes
Thank you for the contribution! The datasource change is great. The resource change should really be implemented as a separate resource, so that we adhere to the design principle of [one TF resource per API object](https://www.terraform.io/docs/extend/hashicorp-provider-design-principles.html#resources-should-represent-a-single-api-object) where we can. Doing it this way would also eliminate the need to use `SetPartial`, which is a deprecated SDK function.

2020-09-18 07:54 UTC, armsnyder commented
You might want to look at PR #421, where we removed the attribute from `gitlab_project`, and the related issue #219

2020-10-12 15:02 UTC, maxenced commented
Hey @horjulf , any chance you can look at that anytime soon ? Or can I do anything to help ? would really love to see this PR moving forward :)

2020-10-13 01:57 UTC, horjulf commented
@maxenced will update it in the next few days, would also like it to get merged.

2020-10-27 16:53 UTC, maxenced commented
> @maxenced will update it in the next few days, would also like it to get merged.

Anything I can help you with ? :)

2020-11-11 20:30 UTC, nicholasklick commented
@horjulf @maxenced any way we can get this wrapped up? Need any help with finishing this?

2020-11-12 08:07 UTC, maxenced commented
> @horjulf @maxenced any way we can get this wrapped up? Need any help with finishing this?

I'm working on this, will create 2 new PR based on the code from @horjulf (one for datasource one for resource).

Maxence

2020-11-13 02:28 UTC, horjulf commented
Sorry for the delay, have been unable to spend time on this.
@maxenced thanks for looking into it.

What I was thinking for the resource:
```hcl
resource "gitlab_group_share_group" "example" {
  group_id = "12345"

  # Allow this to optionally be authoritative, removing any other groups not set here
  authoritative = true|false

  share {
    group_id = "67890"
    access_level    = "guest"
  }
  share {
    ...
  }
}
```

2020-12-01 03:19 UTC, horjulf commented
@maxenced were you able to start working on this ? if not, I have some free time I can spend on this now.

2020-12-01 08:13 UTC, maxenced commented
> @maxenced were you able to start working on this ? if not, I have some free time I can spend on this now.

No sorry did not do anything useful yet for this pr :( cool if you can spend some time on it :)

2020-12-11 04:09 UTC, nicholasklick commented
@horjulf @maxenced  Pinging you both again. Need any help with this? Do you want an Engineer to help with this implementation?

2020-12-11 07:39 UTC, maxenced commented
> @horjulf @maxenced Pinging you both again. Need any help with this? Do you want an Engineer to help with this implementation?

Sadly did not had time to work on it. I hope @horjulf found some time 10 days ago, but I think this PR need help for anybody who can have time to finish it :)

2020-12-14 16:20 UTC, nicholasklick commented
cc @btyy77c

2020-12-28 16:12 UTC, btyy77c commented
Hello! Per the discussion above, I've created a new PR for a `gitlab_group_share_group` resource

https://github.com/gitlabhq/terraform-provider-gitlab/pull/511

Please review and let me know if you see any issues.

Thanks!

2021-01-05 20:12 UTC, horjulf commented
Thank you @btyy77c ! I will close this PR.

2021-01-05 20:12 UTC, closed without merging