gitlab_user: Do not calculate skip_confirmation
gitlabhq/terraform-provider-gitlab pull request #491
Opened 2020-11-23 08:34 UTC by armsnyder

Follow-up on #490 @roidelapluie 

I looked at it again, and I don't think `skip_confirmation` should ever be set during reads or imports, since it is an attribute that only has effect during initial creation.

This change should fix an issue where, if the resource is created with `skip_confirmation=false`, then when the user confirms their email, it would result in an unnecessary resource diff of `skip_confirmation=true`.

2020-11-23 08:38 UTC, roidelapluie commented
If we do not set it on read, it means that it will always be flapping if a user sets it to true.

We might need a suppressdiff function?

2020-11-23 08:39 UTC, armsnyder commented
Hmm, I thought if we don't `d.Set()` it, then it will stay whatever it was originally set to.

2020-11-23 08:41 UTC, roidelapluie commented
> Hmm, I thought if we don't `d.Set()` it, then it will stay whatever it was originally set to.

It will not change the user input on import, would it?

2020-11-23 08:41 UTC, roidelapluie commented
The correct behaviour would be:

1. set it to computed + force_new

2020-11-23 09:12 UTC, armsnyder commented
Updated. That seemed to work.

2020-11-24 10:16 UTC, armsnyder commented
Let's not merge this until #493 is resolved, since I did not run these tests myself locally.

2022-01-23 17:08 UTC, timofurrer requested changes
Needs a rebase, but I think otherwise LGTM. The referenced blocker has also been resolved some time ago.
What do you think @armsnyder ?

2022-01-24 07:31 UTC, timofurrer approved these changes

2022-01-24 07:56 UTC, merged