Added releases event webhook option
gitlabhq/terraform-provider-gitlab pull request #773
Opened 2021-12-27 06:10 UTC by hnaderi

Added releases event option to project webhook resource and updated test and document

2022-02-01 07:33 UTC, timofurrer requested changes
Thanks 🎉 

Looks good to me - can you please rebase to latest master and address the small comment I've left.

2022-02-01 07:33 UTC, timofurrer commented on gitlab/resource_gitlab_project_hook.go
> +			"releases_events": {
Please add the `Description` field here instead of in the Markdown file and run `make reviewable`.

2022-02-01 19:03 UTC, armsnyder approved these changes
lgtm

2022-02-07 11:53 UTC, timofurrer approved these changes

2022-02-07 12:39 UTC, merged