WIP: Add printing_merge_request_link_enabled attribute to projects
gitlabhq/terraform-provider-gitlab pull request #783
Opened 2022-01-17 18:14 UTC by marceloboeira

As mentioned on #782, the field is available on GitLab but still not
possible to use on terraform

Reference:
- https://github.com/gitlabhq/terraform-provider-gitlab/issues/782

2022-01-17 18:24 UTC, marceloboeira commented
This requires https://github.com/xanzy/go-gitlab/pull/1343 to be merged and released, together with an update of the go-gitlab client.

2022-01-17 19:15 UTC, armsnyder commented
Thanks for the PR @marceloboeira. Once that go-gitlab feature is merged, you can feel free to upgrade it as part of this PR. Could you also add that field to the test?

2022-01-17 19:24 UTC, marceloboeira commented
> 

just added to the default of the test, I guess most tests aren't field-specific, but we can add one if that makes sense.

2022-01-17 19:26 UTC, armsnyder commented
Yep, that works. Most of our tests set all the fields, and the in the subsequent "upgrade" test step they change all the fields.

2022-01-24 17:44 UTC, marceloboeira commented
UPDATE 24.01.22

The PR on gitlab client side has been merged, but still need a release so that we can use a "final" release rather than a commit sha.

Once the release is done I can update the code to point to that release and move it forward.

2022-02-07 15:59 UTC, timofurrer commented
@marceloboeira there has been a go-gitlab release some days ago, which we've already integrated. Therefore, I think you could continue here.

Please make also sure to rebase before continuing as we've changed quite some things ;)

2022-02-07 20:23 UTC, marceloboeira commented
thanks @timofurrer, I have rebased/adjusted accordingly hehe hopefully this time is a go

2022-02-07 21:52 UTC, timofurrer requested changes

2022-02-07 21:52 UTC, timofurrer commented on internal/provider/data_source_gitlab_project.go
> +				Description: " Show link to create/view merge request when pushing from the command line",
```suggestion
				Description: "Show link to create/view merge request when pushing from the command line",
```

2022-02-07 21:52 UTC, timofurrer commented on internal/provider/resource_gitlab_project.go
> +		Description: " Show link to create/view merge request when pushing from the command line",
```suggestion
		Description: "Show link to create/view merge request when pushing from the command line",
```

2022-02-07 21:52 UTC, timofurrer commented on internal/provider/data_source_gitlab_project.go
> +				Optional:    true,
```suggestion
				Computed:    true,
```

2022-02-08 07:56 UTC, marceloboeira commented on internal/provider/data_source_gitlab_project.go
> +				Description: " Show link to create/view merge request when pushing from the command line",
sorry, didn't notice those.

2022-02-08 08:34 UTC, armsnyder commented
@marceloboeira As a tip of you didn't know, you can run `make reviewable` to make sure automated checks will pass.

2022-02-08 08:57 UTC, timofurrer approved these changes
lgtm 🎉

2022-02-08 19:18 UTC, marceloboeira commented
@timofurrer I'm going to figure out the specs failing, I believe it's something related to defaults...

2022-02-08 19:55 UTC, marceloboeira commented
> @marceloboeira As a tip if you didn't know, you can run `make reviewable` to make sure automated checks will pass.

somehow that fails, I have to review my gosetup on a new laptop :D

2022-02-08 19:57 UTC, armsnyder commented
> somehow that fails, I have to review my gosetup on a new laptop :D

Could you let us know if you find out, so we can fix or add it to the CONTRIBUTING.md 🙏

2022-02-12 14:13 UTC, marceloboeira commented
@timofurrer @armsnyder finally looking good ehhe

2022-02-14 06:56 UTC, marceloboeira commented on docs/data-sources/project.md
>  - **namespace_id** (Number) The namespace (group or user) of the project. Defaults to your user.
they are not removed...

2022-02-14 07:40 UTC, timofurrer commented on docs/data-sources/project.md
>  - **namespace_id** (Number) The namespace (group or user) of the project. Defaults to your user.
I'm sorry, that seems to be visualization bug in the GitHub mobile up, where they are rendered in some kind of red ^^

Nevermind then, ... 🎉

2022-02-14 07:40 UTC, timofurrer approved these changes
LGTM 🎉

2022-02-14 08:19 UTC, armsnyder approved these changes

2022-02-14 08:27 UTC, merged