Add Pull Request template
gitlabhq/terraform-provider-gitlab pull request #788
Opened 2022-01-23 14:40 UTC by nagyv

Adding a pull request template came up in https://github.com/gitlabhq/terraform-provider-gitlab/pull/786#discussion_r790258026

2022-01-23 14:42 UTC, nagyv commented
@timofurrer Based on your idea. Let me know if you have any suggestions!

2022-01-23 15:04 UTC, timofurrer commented
IMHO: looks good. Even though it contains parts of the `CONTRIBUTING.md`, I'd still reference to it and make sure people have read it :)

2022-01-23 21:12 UTC, armsnyder requested changes

2022-01-23 21:12 UTC, armsnyder commented on .github/pull_request_template.md
> +For a smooth review process, please run through this checklist before submitting a PR.
We can make room for a description to make it easier to fill in. Also we can use comments to hide parts of the template after the PR is opened.

```suggestion
## Description

<!-- Which issue/s does this PR close? Is there any more context you can give the reviewer? -->

## PR Checklist

<!-- For a smooth review process, please run through this checklist before submitting a PR. -->
```

2022-01-24 21:32 UTC, armsnyder approved these changes

2022-01-24 22:08 UTC, merged