Add scripts to locally lint, like ci does
gitlabhq/terraform-provider-gitlab pull request #793
Opened 2022-01-23 16:44 UTC by timofurrer

See #651

2022-01-23 21:58 UTC, armsnyder requested changes

2022-01-23 21:58 UTC, armsnyder commented on GNUmakefile
> +lint:
```suggestion
lint: tfproviderlint
```

2022-01-24 05:57 UTC, armsnyder approved these changes
lgtm

2022-01-24 21:58 UTC, nagyv approved these changes

2022-01-24 21:58 UTC, merged