Add require_password_to_approve option for MRs
gitlabhq/terraform-provider-gitlab pull request #808
Opened 2022-01-27 16:30 UTC by grv87

## Description

Adds `require_password_to_approve` argument to `gitlab_project_level_mr_approvals` resource.

Follow-up for xanzy/go-gitlab#1116

## PR Checklist

- [x] Resource attributes match 1:1 the names and structure of the API resource in [the GitLab API documentation](https://docs.gitlab.com/ee/api/).
- [x] Docs are updated with any new resources or attributes, including how to import the resource.
- [ ] New resources should have at minimum a basic test with three steps: N/A
    - Create the resource
    - Update the attributes
    - Import the resource
- [x] No new `//lintignore` comments that came from copied code. Linter rules are meant to be enforced on new code.

2022-01-27 17:55 UTC, timofurrer submitted a review, later dismissed
Thanks, lgtm if tests pass! 🎉

2022-01-28 02:49 UTC, armsnyder requested changes
Can you rebase and run `make reviewable`? We added `Description` fields to all schemas recently.

2022-02-14 15:18 UTC, timofurrer commented
@grv87 are you still willing to work on this? IHMO it's almost ready for a merge :) If not, we can follow up on it :)

2022-02-24 12:49 UTC, timofurrer commented
I took the liberty and added the necessary changes to get this merged.

2022-02-24 12:50 UTC, timofurrer approved these changes

2022-02-25 06:08 UTC, armsnyder approved these changes

2022-02-25 06:15 UTC, merged