Implement all missing importers
gitlabhq/terraform-provider-gitlab pull request #960
Opened 2022-03-14 19:39 UTC by timofurrer

This change set together with (https://github.com/gitlabhq/terraform-provider-gitlab/pull/954) implements all missing importers and therefore closes the long open #36 .

I've focused on the importer themselves and not so much about the underlying ids. 
I'll follow up with an issue describing the current state of resource ids currently in use. I hope that we can streamline those for v4 of the provider ...

2022-03-14 21:05 UTC, jtymes requested changes

2022-03-14 21:05 UTC, jtymes commented on internal/provider/resource_gitlab_deploy_token.go
> +		return nil, fmt.Errorf("Invalid Deploy Token import format; expected '{type}:{type_id}:{deploy_key_id}' whereas the type can either be a group or project")
```suggestion
		return nil, fmt.Errorf("Invalid Deploy Token import format; expected '{type}:{type_id}:{deploy_token_id}' where the type can either be a group or project")
```

2022-03-14 21:05 UTC, jtymes commented on internal/provider/resource_gitlab_deploy_token.go
> +		return nil, fmt.Errorf("Invalid Deploy Token import format; expected '{type}:{type_id}:{deploy_key_id}' whereas the type can either be a group or project")
```suggestion
		return nil, fmt.Errorf("Invalid Deploy Token import format; expected '{type}:{type_id}:{deploy_token_id}' where the type can either be a group or project")
```

2022-03-14 21:05 UTC, jtymes commented on internal/provider/resource_gitlab_deploy_token.go
> +	typ, type_id, id := s[0], s[1], s[2]
```suggestion
	token_type, type_id, id := s[0], s[1], s[2]
```

2022-03-14 21:31 UTC, jtymes commented on internal/provider/resource_gitlab_deploy_token.go
> +	typ, type_id, id := s[0], s[1], s[2]
Thinking about this more, it seems like it should be `tokenType` and `typeID`.

2022-03-15 08:17 UTC, timofurrer commented
@jtymes good catches, thanks for the review!

2022-03-15 09:25 UTC, armsnyder approved these changes

2022-03-15 09:26 UTC, merged